CREATE TABLE  "DOCTOR" 
   (	"ID" NUMBER(15,0), 
	"NAME" VARCHAR2(100), 
	"E_MAIL" VARCHAR2(100), 
	"PASSWORD" VARCHAR2(100), 
	"DEPT_NO" NUMBER(15,0), 
	 CONSTRAINT "DOCTOR_CON1" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "DOCTOR_CON2" UNIQUE ("E_MAIL") ENABLE
   ) ;ALTER TABLE  "DOCTOR" ADD CONSTRAINT "DOCTOR_CON" FOREIGN KEY ("DEPT_NO")
	  REFERENCES  "DEPARTMENT" ("ID") ENABLE;


CREATE TABLE  "PATIENT" 
   (	"ID" NUMBER(15,0), 
	"SSN" NUMBER(15,0), 
	"NAME" VARCHAR2(100), 
	"E_MAIL" VARCHAR2(100), 
	"PASSWORD" VARCHAR2(100), 
	"BIRTH_DATE" DATE, 
	"GENDER" VARCHAR2(100), 
	 CONSTRAINT "PATIENT_CON" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "PATIENT_CON21" UNIQUE ("E_MAIL", "SSN") ENABLE
   ) ;

CREATE TABLE  "DEPARTMENT" 
   (	"ID" NUMBER(15,0), 
	"NAME" VARCHAR2(100), 
	 CONSTRAINT "DEPT_CON" PRIMARY KEY ("ID") ENABLE
   ) ;

CREATE TABLE  "APPOINTMENTS" 
   (	"ID" NUMBER, 
	"PID" NUMBER, 
	"DID" NUMBER, 
	"WHEN" TIMESTAMP (6) NOT NULL ENABLE, 
	"FEE" NUMBER, 
	 PRIMARY KEY ("ID") ENABLE
   ) ;ALTER TABLE  "APPOINTMENTS" ADD CONSTRAINT "APPOINTMENTS_CON" FOREIGN KEY ("PID")
	  REFERENCES  "PATIENT" ("ID") ENABLE;ALTER TABLE  "APPOINTMENTS" ADD CONSTRAINT "APPOINTMENTS_CON2" FOREIGN KEY ("DID")
	  REFERENCES  "DOCTOR" ("ID") ENABLE;



			
	
	